import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Resend } from "https://esm.sh/resend@3.2.0";
import { create } from "https://deno.land/x/djwt@v3.0.2/mod.ts";

/* ----------------------------------------
   Utilities
---------------------------------------- */

function formatDateReadable(dateStr: string): string {
  const date = new Date(`${dateStr}T00:00:00`);
  return date.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function normalizeTimeInput(rawTime: string): string {
  if (!rawTime) throw new Error("Missing booking time");

  const cleanedTime = rawTime.trim();

  // Match HH:MM or H:MM optionally with seconds
  const match = cleanedTime.match(/^(\d{1,2}):(\d{2})/);

  if (!match) {
    throw new Error(`Invalid time format: ${rawTime}`);
  }

  let hours = Number(match[1]);
  const minutes = Number(match[2]);

  if (hours > 23 || minutes > 59) {
    throw new Error(`Invalid time value: ${rawTime}`);
  }

  // Ensure leading zero for ISO format
  const safeHours = String(hours).padStart(2, "0");

  return `${safeHours}:${minutes.toString().padStart(2, "0")}`;
}

function addMinutes(baseIsoDateTime: string, minutesToAdd: number): string {
  const parsedDate = new Date(baseIsoDateTime);

  if (Number.isNaN(parsedDate.getTime())) {
    throw new Error(`Invalid date passed to addMinutes(): ${baseIsoDateTime}`);
  }

  parsedDate.setMinutes(parsedDate.getMinutes() + minutesToAdd);

  return parsedDate.toISOString();
}

/* ----------------------------------------
   Google Auth
---------------------------------------- */

async function getGoogleAccessToken(): Promise<string> {
  const clientEmail = Deno.env.get("GOOGLE_SERVICE_ACCOUNT_EMAIL");

  const privateKeyPem = Deno.env
    .get("GOOGLE_PRIVATE_KEY")
    ?.replace(/\\n/g, "\n")
    .trim();

  // console.log("Email:", clientEmail);
  // console.log("Key exists:", !!privateKeyPem);

  if (!clientEmail || !privateKeyPem) {
    throw new Error("Missing Google service account credentials");
  }

  // 🔥 Convert PEM → ArrayBuffer
  const pemContents = privateKeyPem
    .replace("-----BEGIN PRIVATE KEY-----", "")
    .replace("-----END PRIVATE KEY-----", "")
    .replace(/\s/g, "");

  const binaryDer = Uint8Array.from(atob(pemContents), (c) => c.charCodeAt(0));

  // 🔥 Import as CryptoKey
  const cryptoKey = await crypto.subtle.importKey(
    "pkcs8",
    binaryDer.buffer,
    {
      name: "RSASSA-PKCS1-v1_5",
      hash: "SHA-256",
    },
    false,
    ["sign"],
  );

  const now = Math.floor(Date.now() / 1000);

  const jwt = await create(
    { alg: "RS256", typ: "JWT" },
    {
      iss: clientEmail,
      scope: "https://www.googleapis.com/auth/calendar",
      aud: "https://oauth2.googleapis.com/token",
      iat: now,
      exp: now + 3600,
    },
    cryptoKey,
  );

  const res = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
      assertion: jwt,
    }),
  });

  const data = await res.json();

  if (!data.access_token) {
    throw new Error(JSON.stringify(data));
  }

  return data.access_token;
}

/* ----------------------------------------
   Google Calendar
---------------------------------------- */

async function createCalendarEvent(params: {
  accessToken: string;
  calendarId: string;
  name: string;
  email: string;
  bookingDate: string;
  bookingTime: string;
}) {
  const normalizedTime = normalizeTimeInput(params.bookingTime);
  const startDateTime = `${params.bookingDate}T${normalizedTime}:00`;
  // manually calculate end time (30 minutes)
  const [hours, minutes] = normalizedTime.split(":").map(Number);
  const endMinutes = hours * 60 + minutes + 30;

  const endHours = Math.floor(endMinutes / 60) % 24;
  const endMins = endMinutes % 60;

  const endDateTime = `${params.bookingDate}T${String(endHours).padStart(2, "0")}:${String(endMins).padStart(2, "0")}:00`;

  const eventPayload: any = {
    summary: `Free Strategy Session – ${params.name}`,
    // description: `Client Email: ${params.email}`,//use for dynamic meet links in calendar
    description: `Client Email: ${params.email}\nMeeting Link: ${Deno.env.get("DEFAULT_MEETING_LINK")}`, //Meet link appears inside Google Calendar (static).
    start: {
      dateTime: startDateTime,
      timeZone: "Africa/Lagos",
    },
    end: {
      dateTime: endDateTime,
      timeZone: "Africa/Lagos",
    },
    // Use when you want to add attendees (requires proper permissions and sharing settings)
    // attendees: [{ email: params.email }],
  };

  // 🔐 Attempt Meet creation ONLY if supported (use for autogenerated meet links)

  // try {
  //   eventPayload.conferenceData = {
  //     createRequest: {
  //       requestId: crypto.randomUUID(),
  // conferenceSolutionKey: {
  //   type: "hangoutsMeet",
  // },
  //     },
  //   };
  // } catch {
  //   // silently ignore
  // }

  // Use when you want to create events with Meet links (simpler, more reliable, auto Meet generation)

  // const res = await fetch(
  //   `https://www.googleapis.com/calendar/v3/calendars/${params.calendarId}/events?conferenceDataVersion=1`,

  // Use when you want to create events without Meet links (simpler, more reliable, but no auto Meet generation)
  const res = await fetch(
    `https://www.googleapis.com/calendar/v3/calendars/${params.calendarId}/events`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${params.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(eventPayload),
    },
  );

  const data = await res.json();

  if (!res.ok) {
    throw new Error(`Calendar event error: ${JSON.stringify(data)}`);
  }
  //  Manually set a default meeting link if Meet creation fails or is unsupported
  const meetLink = Deno.env.get("DEFAULT_MEETING_LINK") || null;

  // Use when you want to Autogenerate Meet links (requires proper conferenceData setup and permissions)

  // const meetLink =
  //   data.conferenceData?.entryPoints?.find(
  //     (entry: any) => entry.entryPointType === "video",
  //   )?.uri || null;

  return {
    eventId: data.id,
    meetLink,
  };
}

/* ----------------------------------------
   Main Function
---------------------------------------- */

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers":
          "authorization, x-client-info, apikey, content-type",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
      },
    });
  }

  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  try {
    const {
      name,
      phone,
      email,
      businessName,
      message,
      bookingDate,
      bookingTime,
    } = await req.json();

    if (
      !name ||
      !email ||
      !bookingDate ||
      !bookingTime ||
      !/^\S+@\S+\.\S+$/.test(email) ||
      !/^\d{4}-\d{2}-\d{2}$/.test(bookingDate)
    ) {
      return new Response(JSON.stringify({ error: "Missing fields" }), {
        status: 400,
        headers: { "Access-Control-Allow-Origin": "*" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Prevent double booking
    const { data: existing } = await supabase
      .from("bookings")
      .select("id")
      .eq("booking_date", bookingDate)
      .eq("booking_time", bookingTime)
      .maybeSingle();

    if (existing) {
      return new Response(JSON.stringify({ error: "Time slot taken" }), {
        status: 409,
        headers: { "Access-Control-Allow-Origin": "*" },
      });
    }

    // ✅ INSERT FIRST (ALWAYS)
    const { data: booking, error } = await supabase
      .from("bookings")
      .insert({
        name,
        email,
        phone,
        business_name: businessName,
        message,
        booking_date: bookingDate,
        booking_time: bookingTime,
        status: "confirmed",
      })
      .select()
      .single();

    if (error) throw error;
    if (!booking) throw new Error("Booking insertion failed");
    // console.log("New booking created, ID:", booking.id);

    // ---------- Google Calendar Sync (non-blocking)
    let calendarResult = {
      eventId: null as string | null,
      meetLink: Deno.env.get("DEFAULT_MEETING_LINK") || null,
    };

    try {
      const accessToken = await getGoogleAccessToken();

      calendarResult = await createCalendarEvent({
        accessToken,
        calendarId: Deno.env.get("GOOGLE_CALENDAR_ID")!,
        name,
        email,
        bookingDate,
        bookingTime,
      });

      await supabase
        .from("bookings")
        .update({
          google_event_id: calendarResult.eventId,
          google_meet_link: calendarResult.meetLink,
        })
        .eq("id", booking.id);
    } catch (err) {
      console.error("Calendar sync failed:", err);
    }

    // ---------- Emails (non-blocking)
    const resend = new Resend(Deno.env.get("RESEND_API_KEY")!);
    resend.emails
      .send({
        /* business email */
        from: "Free Strategy Session <bookings@mcraytechservices.com>",
        to: ["solutions@mcraytechservices.com"],
        subject: "📅 New Booking Received",
        html: `
     <h2>Free Strategy Session Booking</h2>
     <p><strong>Name:</strong> ${name}</p>
     <p><strong>Email:</strong> ${email}</p>
     <p><strong>Phone:</strong> ${phone || "N/A"}</p>
     <p><strong>Business:</strong> ${businessName || "—"}</p>
     <p><strong>Date:</strong> ${formatDateReadable(bookingDate)}</p>
     <p><strong>Time:</strong> ${bookingTime} (WAT)</p>
     <p><strong>Meeting Link:</strong><br>
     ${
       calendarResult.meetLink
         ? `<a href="${calendarResult.meetLink}">${calendarResult.meetLink}</a>`
         : "Meeting link will be shared shortly"
     }
    </p>
     <p><strong>Message:</strong> ${message || "None"}</p>
   `,
      })
      .catch(console.error);
    resend.emails
      .send({
        /* client email */
        from: "McRay Tech Services <bookings@mcraytechservices.com>",
        to: [email],
        subject: "Booking Confirmed",
        html: `
     <p>Hello ${name}, <br><br>
     Thank you for booking a free strategy session with us!</p>
     <h3>This session is designed to:</h3>
     <ul>
      <li>Learn more about your business, goals, and identify key challenges in your business operations</li><br>
      <li>Explore opportunities for growth and efficiency</li><br>
      <li>Develop a strategic plan tailored to your needs</li><br>
      <li>Answer any questions you may have about services</li><br>
     </ul>
      <h3>Your booking details:</h3>
      <p><strong>Date:</strong> ${formatDateReadable(bookingDate)}</p>
      <p><strong>Time:</strong> ${bookingTime} (WAT)</p>
      <p><strong>Meeting Link:</strong><br>
      ${
        calendarResult.meetLink
          ? `<a href="${calendarResult.meetLink}">${calendarResult.meetLink}</a>`
          : "Meeting link will be shared shortly"
      }
      </p>
      <h3>Preparation Tips:</h3>
      <p>Please make sure you're in a quiet space and bring along any key information you'd like us to know about your business.</p>
      <p>If you need to reschedule, please contact us. We look forward to seeing you.</p><br>
      <p>— McRay Tech Services Team 🖤</p>
   `,
      })
      .catch(console.error);

    return new Response(
      JSON.stringify({
        success: true,
        booking,
        meetLink: calendarResult.meetLink,
      }),
      { status: 200, headers: { "Access-Control-Allow-Origin": "*" } },
    );
  } catch (err) {
    console.error("BOOKING ERROR:", err);
    return new Response(JSON.stringify({ error: "Internal Server Error" }), {
      status: 500,
      headers: { "Access-Control-Allow-Origin": "*" },
    });
  }
});
